In [1]:
a = [1,2,3,4 , 5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [2]:
import numpy as np

arr = np.array([1,2, 3,4,5])
print(arr)
print(type (arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# import the library
import numpy as np
arr = np.array([[[1 , 2, 3 ],[2,3,4] , [4,5,6]]])
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
# ndim define the dimension of array
print(arr.ndim)

3


In [5]:
# find the type of individual of element will float
arr = np.array([1 , 2, 3 ] , dtype = "f")
print(type(arr[2]))
print(arr)

<class 'numpy.float32'>
[1. 2. 3.]


In [6]:
# data type string
arr = np.array([1 , 2, 3 ] , dtype = "S")
print(type(arr[2]))
print(arr)

<class 'numpy.bytes_'>
[b'1' b'2' b'3']


In [7]:
# data type integer
arr = np.array([1 , 2, 3 ] , dtype = "i")
print(type(arr[2]))
print(arr)

<class 'numpy.intc'>
[1 2 3]


In [8]:
# No: of element in the array // Size
arr = np.array([1 , 2 , 3  , 4 , 5])
print((arr.size))

5


In [9]:
# item size of array
print(arr.itemsize)

4


In [10]:
# numpy array size
print(arr.size * arr.itemsize  )

20


In [11]:
# 2D array define dimension
arr = np.array([[[1,2,3] , [4,5,6]]])
print(arr.ndim)

3


In [12]:
# define rows and column in 2D array  (rows , column) 
arr = np.array([[1,2] , [4,5] , [6,7]])
print(arr.shape)

(3, 2)


In [13]:
# print (row) through index
print(arr[1])

[4 5]


In [14]:
# print individual element in 2D array
print(arr[1][0])

4


In [15]:
# range of array in 2D array (include , exclude)
arr = np.arange(1,10)
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [16]:
# range of array  with step in 2D array (include , exclude)
arr = np.arange(1, 11 , 2)
print(arr)

[1 3 5 7 9]


In [17]:
# range of array  with step in 2D array (include , exclude)
arr = np.arange(10, 0 , -1)
print(arr)

[10  9  8  7  6  5  4  3  2  1]


In [55]:
# make 2D array by range // method : reshape(row , column)
arr = np.arange(1,16).reshape(3,5)                 # 3* 5 = 15(element)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [58]:
# identity method
arr = np.identity(3)   #float , diagonal = 1 , 2D array , square
print(arr)            
print(arr.ndim)      
print(arr.size)
print(arr.shape)
print(type(arr))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2
9
(3, 3)
<class 'numpy.ndarray'>


In [32]:
# identity method by eye method
arr = np.eye(3, 5)   #float , principle_diagonal = 1 , 2D array , square
print(arr)            


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [61]:
# All element One
arr = np.ones((3,4) , dtype = "i")
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [62]:
# All element zero
arr = np.zeros((3,4) , dtype = "i")
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [63]:
# All element One
arr = np.ones(3) # (3,1) , by default data type will float
print(arr)

[1. 1. 1.]


In [67]:
# 2d array of fixed value 
arr = np.full((4,3) , 5 , dtype = "f")
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [68]:
# identity all element in array is non_zero 
# if non_zero o/p will True otherwise False
arr = np.array([1,1,2,2,4,4,0,5,5])
np.all(arr)  # one element is zero answer : False

False

In [70]:
arr = np.array([1,1,2,2,4,4,1,5,5])
np.all(arr)   # all element is non_Zero

True

In [78]:
# compare 2 arrays 
import numpy as np
arr1 = np.array([1,5])  # 1 compare to 2 = False , 5 compare to 5 = True
arr2 = np.array([2,5])

print(np.greater_equal(arr1 , arr2))

[False  True]


In [80]:
# compare 2 arrays 
import numpy as np
arr1 = np.array([1,5])  # 1 less to 2 = True , 5 less to 5 = False
arr2 = np.array([2,5])

print(np.less(arr1 , arr2))

[ True False]


In [83]:
# compare 2 arrays 
import numpy as np
arr1 = np.array([1,5])  # 1 less_equal 2 = True , 5 less_equal to 5 = True
arr2 = np.array([2,5])

print(np.less_equal(arr1 , arr2))

[ True  True]


In [84]:
# sum to all element in the  array
arr = np.array([1 ,2 ,3,4,5]) # 1+ 2+ 3+4+5 = 15
print(np.sum(arr))

15


In [18]:
# sum row to column in 2D array   // 1+3 = 4 , 2+4 = 6
arr = np.array([[1,2],[3,4]])
print(arr)
print(np.sum(arr , axis = 0))

[[1 2]
 [3 4]]
[4 6]


In [20]:
# sum row to column in 2D array   // 1+2 = 3 , 3+4 = 7
arr = np.array([[1,2],[3,4]])
print(arr)
print(np.sum(arr , axis = 1))

[[1 2]
 [3 4]]
[3 7]


In [22]:
# sorted 1D array
arr = np.array([ 2,1,4,3,5])
print(np.sort(arr))

[1 2 3 4 5]


In [28]:
# In 2D array it sorted column vise // compare 2 to `1` & compare 3 to 1
arr = np.array([[2,1],[3,1]])
print(np.sort(arr , axis = 1))


[[1 2]
 [1 3]]


In [5]:
# find values of array which is greater then specific value
import numpy as np
arr = np.array([[1.1,4.4 ,7.7] , [2.2,5.5, 8.8] , [3.3,6.6,9.9]])
arr1 = arr[arr > 3.3]  # > 3.3 value print
arr2 = np.sort(arr1)
print(arr2)

[4.4 5.5 6.6 7.7 8.8 9.9]


In [6]:
# find values of array which is less then specific value
import numpy as np
arr = np.array([[1.1,4.4 ,7.7] , [2.2,5.5, 8.8] , [3.3,6.6,9.9]])
arr1 = arr[arr < 3.3]  # < 3.3 value print
print(arr1)

[1.1 2.2]


In [7]:
# find values of array which is equal to specific value
import numpy as np
arr = np.array([[1.1,4.4 ,7.7] , [2.2,5.5, 8.8] , [3.3,6.6,9.9]])
arr1 = arr[arr == 3.3]  # ==  3.3 value print
print(arr1)

[3.3]


In [8]:
# find values of array which is less then specific value
import numpy as np
arr = np.array([[1.1,4.4 ,7.7] , [2.2,5.5, 8.8] , [3.3,6.6,9.9]])
arr1 = arr[arr < 1.1]  # [] empty index print
print(arr1)

[]


In [9]:
# multiplication of 2D arrays // Matrix size should be same
arr1 = np.array([[6,8,4] , [4,7,2]])
arr2 = np.array([[1,4,2] , [9,5,7]])

print(np.multiply(arr1 , arr2))

[[ 6 32  8]
 [36 35 14]]


In [11]:
# dot product but (m,n) = (n,m)
arr1 = np.array([[6,8,4] , [4,7,2]])  # 2 rows and 3 column
arr2 = np.array([[1,4] , [9,5] , [6,7]])   # 3 rows and 2 column

print(np.dot(arr1 , arr2))

[[102  92]
 [ 79  65]]


In [19]:
# numpy array to an image and vice versa
import numpy as np
Image = np.array([[0 , 1 , 0 , 1 , 0 , 1 , 0],
                  [1 , 0 , 1 , 0 , 1 , 0 , 1],
                  [0 , 1 , 0 , 1 , 0 , 1 , 0],
                  [1 , 0 , 1 , 0 , 1 , 0 , 1],
                  [0 , 1 , 0 , 1 , 0 , 1 , 0]])
print(Image)


[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]


In [ ]:
import matplotlib.pyplot as plt

plt.imshow(Image , cmap = "gray")
plt.title("Binary image")
plt.axis("off")

plt.show()


In [31]:
# line_space between array element 
arr = np.linspace(1 , 100 , 5)     #(start , stop , value_quantity )
print(arr)

[  1.    25.75  50.5   75.25 100.  ]


In [24]:
# 3d array
arr = np.array([[[1,2,3],[2,3,4]] ,[[5,6,7],[7,8,9]]])
print(arr)

[[[1 2 3]
  [2 3 4]]

 [[5 6 7]
  [7 8 9]]]


In [33]:
# diagonal matrix
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [34]:
# diagonal matrix
arr = np.diag([1,2,3] , 1) # 1st column and last row empty
print(arr)

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [35]:
# find diagonal element
arr = np.array([[1,2],[3,4]])
print(np.diag(arr))

[1 4]


In [40]:
# line_space ([rows] , column)        # x^2-1 = x = 1
arr = np.vander([1,2,3] , 2)         # x^2-2 = 1
print(arr)                           # x2-3 = -x = 1

[[1 1]
 [2 1]
 [3 1]]


In [48]:
# vandermonde
import numpy as np
arr = np.vander(np.linspace(0,2,5) , 2)
print(arr)

[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]


In [50]:
# vandermonde matrix

arr = np.vander((1,2,3,4) , 4)   # (1,2,3,4) is i/p or "x"  & 4 = column or power
print(arr)          # First column: 𝑥4−1=𝑥3 , Second column:x4−2=x2 ,Third column: x4−3=x1=x , Fourth column: x4−4=x0=1
                    # 2^4-1 = 8 , 2^3-1 = 4 , 2^2-1 = 2 , 2^1-1 = 1

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [52]:
# 3D in zeros(block , rows , column)
arr = np.zeros((2,3,2))  # apply as same as on ones
print(arr)                

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [60]:
# random number   , numpy.random is module and default_rng is function
import numpy as np
from numpy.random import default_rng 
arr = default_rng(42).random((3,2))
print(arr)

[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]


In [61]:
# random(blocks , row , column)
from numpy.random import default_rng
arr = default_rng(42).random((2,3,2))   # 42  generate same random value always when program run
print(arr)

[[[0.77395605 0.43887844]
  [0.85859792 0.69736803]
  [0.09417735 0.97562235]]

 [[0.7611397  0.78606431]
  [0.12811363 0.45038594]
  [0.37079802 0.92676499]]]


In [63]:
"""Indices method : First array (row indices) → Each row contains the same row index.
                  :Second array (column indices) → Each column contains its own column index"""

arr = np.indices((4,4))  # o/p The output shape will be (2, 4, 4)
print(arr)

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


In [64]:
# slice view
a = np.array([1,2,3,4,5])
b = a[:2]   # b = [1 , 2]
b += 1      # b= [1 ,2] to [2,3]
print("a = " , a, "b = " ,b) # it doesn't copy so it also effect a

a =  [2 3 3 4 5] b =  [2 3]


In [65]:
# Replicate (copy) method
a = np.array([1,2,3,4,5])
b = a[:2].copy() # now it will not effect "a" b/c a is copy for "b"
b += 1
print("a = " , a, "b = " ,b)

a =  [1 2 3 4 5] b =  [2 3]


In [70]:
# join to 2 arrays or multi arrays 
A = np.ones((2,2))
B = np.zeros((2,2))
C = np.eye(2,2)
D = np.full((2,2) ,5)

arr = np.block([[A,B] , [C,D]])   # join A+B , C+D
print(arr)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 5. 5.]
 [0. 1. 5. 5.]]


In [91]:
# join by "vstack " : Vertical stack (join row vise and column should same)
arr1 = np.array([[1,2] , [3,4]])
arr2 = np.array([5,6])
                                    # it used for 1D and 2D 
arr = np.vstack((arr1 , arr2))     # 2 different array combine row wise          
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [82]:
# join by "hstack": Horizontal stack (Row should be same)
arr1 = np.array([1,2 ,3 , 4 ,5])
arr2 = np.array([6,7])

arr = np.hstack((arr1 , arr2)) # Since a and b are 1D, they are concatenated into a single row.
print(arr)

[1 2 3 4 5 6 7]


In [90]:
# hstack for multiple array
arr1 = np.array([[1,2] , [5,6]])
arr2 = np.array([[3,4] ,[7,8]])

result = np.hstack((arr1 , arr2)) # Since a and b are 2D, they are concatenated into a 1st row into 1st row and vise versa.
print(result)

[[1 2 3 4]
 [5 6 7 8]]
